include:
  - proxy.yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER:-app}
      - DB_PASSWORD=${MYSQL_PASSWORD:-very_strong}
      - DB_NAME=${MYSQL_DATABASE:-example}
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always
  
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-example}
      - MYSQL_USER=${MYSQL_USER:-app}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-very_strong}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_ROOT_HOST=%
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: on-failure

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

